// next-app/components/FeedList.tsx
/**
 * [INPUT]: feeds, feedIndex, selectedFeed
 * [OUTPUT]: Rendered feed navigation list
 * [POS]: next-app/components/ Left sidebar component
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

import { useMemo } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { Calendar, ChevronLeft } from 'lucide-react'
import { Feed, FeedItem } from '@/hooks/useFeeds'
import { isToday, isYesterday } from '@/lib/date'

interface FeedListProps {
  feedIndex: FeedItem[]
  feeds: Map<string, Feed>
  selectedFeed: string
  onSelect: (feedId: string) => void
  loadingIndex: boolean
  error: string | null
}

export function FeedList({ feedIndex, feeds, selectedFeed, onSelect, loadingIndex, error }: FeedListProps) {
  // Calculate counts
  const todayCount = useMemo(() => {
    let count = 0
    feeds.forEach(feed => {
      feed.items?.forEach(item => {
        if (isToday(item.date_published)) count++
      })
    })
    return count
  }, [feeds])

  const yesterdayCount = useMemo(() => {
    let count = 0
    feeds.forEach(feed => {
      feed.items?.forEach(item => {
        if (isYesterday(item.date_published)) count++
      })
    })
    return count
  }, [feeds])

  const getFeedCount = (feedId: string) => {
    return feeds.get(feedId)?.items?.length || 0
  }

  const hasTodayUpdate = (feedId: string) => {
    const feedData = feeds.get(feedId)
    if (!feedData?.items) return false
    return feedData.items.some(item => isToday(item.date_published))
  }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <div className="p-4 border-b border-border flex items-center justify-between flex-shrink-0">
        <h2 className="font-semibold">订阅源</h2>
        <span className="text-xs text-muted-foreground">{feedIndex.length} 个</span>
      </div>
      <div className="flex-1 overflow-y-auto">
        <div className="p-2 space-y-1">
          {error && (
            <div className="p-2 mb-2 text-xs text-destructive bg-destructive/10 rounded">
              加载错误: {error}
            </div>
          )}
          <Button
            variant={selectedFeed === 'today' ? "secondary" : "ghost"}
            className="w-full justify-start font-normal"
            onClick={() => onSelect('today')}
          >
            <Calendar className="mr-2 h-4 w-4" />
            <span className="flex-1 text-left">今日</span>
            {todayCount > 0 && <Badge variant="secondary" className="ml-auto text-xs">{todayCount}</Badge>}
          </Button>
          <Button
            variant={selectedFeed === 'yesterday' ? "secondary" : "ghost"}
            className="w-full justify-start font-normal"
            onClick={() => onSelect('yesterday')}
          >
            <ChevronLeft className="mr-2 h-4 w-4" />
            <span className="flex-1 text-left">昨日</span>
            {yesterdayCount > 0 && <Badge variant="secondary" className="ml-auto text-xs">{yesterdayCount}</Badge>}
          </Button>

          <Separator className="my-2" />

          {loadingIndex ? (
            <div className="p-4 text-center text-sm text-muted-foreground">加载中...</div>
          ) : (
            feedIndex.map(feed => {
              const hasUpdate = hasTodayUpdate(feed.id)
              return (
                <Button
                  key={feed.id}
                  variant={selectedFeed === feed.id ? "secondary" : "ghost"}
                  className="w-full justify-start font-normal truncate"
                  onClick={() => onSelect(feed.id)}
                >
                  {hasUpdate && (
                    <span className="mr-2 flex-shrink-0 w-2 h-2 rounded-full bg-blue-500 animate-pulse" title="今日有更新" />
                  )}
                  <span className="truncate flex-1 text-left">{feed.name}</span>
                  {getFeedCount(feed.id) > 0 && (
                    <span className="ml-2 text-xs text-muted-foreground">{getFeedCount(feed.id)}</span>
                  )}
                </Button>
              )
            })
          )}
        </div>
      </div>
    </div>
  )
}

// docs/.vitepress/theme/components/FeedList.vue
<template>
  <aside class="sidebar">
    <div class="sidebar-header">
      <h2 class="feed-list-title">订阅源</h2>
      <span class="total-count" v-if="totalCount > 0">{{ totalCount }} 篇</span>
    </div>
    <ul class="feed-list">
      <li
        class="feed-item"
        :class="{ active: selectedFeed === 'all' }"
        @click="selectFeed('all')"
      >
        <span class="feed-icon">📅</span>
        <span class="feed-name">今日</span>
        <span class="feed-count" v-if="todayCount > 0">({{ todayCount }})</span>
      </li>
      <li
        class="feed-item"
        :class="{ active: selectedFeed === 'yesterday' }"
        @click="selectFeed('yesterday')"
      >
        <span class="feed-icon">⏮️</span>
        <span class="feed-name">昨日</span>
        <span class="feed-count" v-if="yesterdayCount > 0">({{ yesterdayCount }})</span>
      </li>
      <li
        v-for="feed in feedIndex"
        :key="feed.id"
        class="feed-item"
        :class="{ active: selectedFeed === feed.id }"
        @click="selectFeed(feed.id)"
      >
        <span class="feed-icon">📄</span>
        <span class="feed-name">{{ feed.name }}</span>
        <span class="feed-count" v-if="getFeedCount(feed.id) > 0">
          ({{ getFeedCount(feed.id) }})
        </span>
      </li>
    </ul>
  </aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { FeedIndex, Feed } from '../composables/useFeeds'

const props = defineProps<{
  feedIndex: FeedIndex[]
  feeds: Map<string, Feed>
  selectedFeed: string
}>()

const emit = defineEmits<{
  'update:selectedFeed': [feedId: string]
}>()

const totalCount = computed(() => {
  let count = 0
  props.feeds.forEach(feed => {
    count += feed.items?.length || 0
  })
  return count
})

const todayCount = computed(() => {
  let count = 0
  const today = new Date().toDateString()

  props.feeds.forEach(feed => {
    feed.items?.forEach(item => {
      if (new Date(item.date_published).toDateString() === today) {
        count++
      }
    })
  })
  return count
})

const yesterdayCount = computed(() => {
  let count = 0
  const yesterday = new Date()
  yesterday.setDate(yesterday.getDate() - 1)
  const yesterdayStr = yesterday.toDateString()

  props.feeds.forEach(feed => {
    feed.items?.forEach(item => {
      if (new Date(item.date_published).toDateString() === yesterdayStr) {
        count++
      }
    })
  })
  return count
})

function getFeedCount(feedId: string): number {
  const feed = props.feeds.get(feedId)
  return feed?.items?.length || 0
}

function selectFeed(feedId: string) {
  emit('update:selectedFeed', feedId)
}
</script>

<style scoped>
.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 0.75rem;
  margin-bottom: 1rem;
}

.feed-list-title {
  font-size: 1.1rem;
  font-weight: 600;
  margin: 0;
  color: var(--vp-c-text-1);
}

.total-count {
  font-size: 0.85rem;
  color: var(--vp-c-text-3);
  font-weight: 400;
}

.feed-icon {
  font-size: 1rem;
  flex-shrink: 0;
}

.feed-name {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.feed-count {
  font-size: 0.75rem;
  color: var(--vp-c-text-3);
  flex-shrink: 0;
}
</style>
